---
version: 2
updates:
  - package-ecosystem: bundler
    commit-message:
      prefix: 'chore: '
    directory: '/'
    schedule:
      interval: daily
      time: '08:00'
      timezone: US/Central
