branches:
  only:
    - master

language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

before_install:
  - gem update --system
  - gem --version

bundler_args: --binstubs --jobs 3 --retry 3

cache: bundler

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile

script: "bin/rspec"
