before_install:
  - gem update --system
  - gem --version
branches:
  only:
    - master
bundler_args: --binstubs --jobs 3 --retry 3
cache: bundler
gemfile:
  - gemfiles/Gemfile-rails-4.2
  - gemfiles/Gemfile-rails-5.0
  - gemfiles/Gemfile-rails-5.1
  - gemfiles/Gemfile-rails-5.2
  - gemfiles/Gemfile-rails-6.0
language: ruby
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/Gemfile-rails-6.0
rvm:
  - 2.4
  - 2.5
  - 2.6
script: "bin/rspec"
