branches:
  only:
    - master

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

before_install:
  - gem update --system
  - gem --version

bundler_args: --binstubs --jobs 3 --retry 3

cache: bundler

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

script: "bin/rspec"
