---
before_install:
  - gem update --system
  - gem --version
branches:
  only:
    - master
bundler_args: --binstubs --jobs 3 --retry 3
cache: bundler
gemfile:
  - gemfiles/Gemfile-rails-5.2
  - gemfiles/Gemfile-rails-6.0
language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
script: "bin/rspec"
